### PR TITLE
fix: recognize p2p-circuit addresses without trailing peerId

### PR DESCRIPTION
**Pull request by SgtPooki**
Found a bug in Circuit matcher when playing around with DCUtR PR https://github.com/libp2p/js-libp2p/pull/1928#issuecomment-1672474715

failing test: https://github.com/multiformats/js-multiaddr-matcher/actions/runs/5816447592/job/15769587364?pr=2#step:5:41

fixes https://github.com/multiformats/js-multiaddr-matcher/issues/3

### CODE REVIEW

**Comment by achingbrain** [comment]
The trailing peer id is necessary to know which peer you're trying to dial via the relay.

The format is: `/ip4/{IP}/tcp/{port}/p2p/{relayPeer}/p2p-circuit/p2p/{targetPeer}`

If `/p2p/{targetPeer}` is omitted you just have the relay address which isn't enough to dial a peer since multiple targets can have a reservation on the same relay so it's not really a valid address.

**Comment by achingbrain** [comment]
> Then it seems like even though the "good circuit" addresses aren't dialable, they're valid..

I would disagree, these are invalid addresses since the PeerID is required but missing, like `/ip4/123.123.123.123/tcp` is invalid since the TCP port number is missing.

**Comment by SgtPooki** [comment]
> I would disagree, these are invalid addresses since the PeerID is required but missing, like `/ip4/123.123.123.123/tcp` is invalid since the TCP port number is missing.

Ok, thanks for confirming. 

Also, I want to solidify a path to unblock uses like https://github.com/libp2p/js-libp2p/blob/feat/dcutr/packages/libp2p/src/dcutr/dcutr.ts#L224-L242 without other devs/users having to "append the destination peer id [them]selves," or at least knowing when they _should_.

There seems to be at least one bug, and I've listed potential misalignment below. Please let me know if I'm mistaken:

1. We shouldn't have to do https://github.com/libp2p/js-libp2p/blob/7d1c0214934386d434a190cd5a808cf0517844aa/packages/libp2p/src/dcutr/dcutr.ts#L233-L236. This should be populated in peerInfo
    * Potential bug: `peerStore.get(peerId)` doesn't return valid multiaddrs with full peerInfo. 
2. there are two different types of multiaddrs: dialable (`Multiaddr`: full multiaddr with peerId)  and peer-dependent sub-multiaddrs (`PeerMultiaddr`: multiaddrs returned for a peer that doesn't contain the peerId simply for saving space on the wire or otherwise)
    * Potential bug: We don't have `@multiformats/multiaddr-matchers` for the two separate types
    * Potential bug: We don't have a separate type for when our library is returning a multiaddr that is dialable as is or not (e.g. `Multiaddr`, `PeerMultiaddr`)
3. Potential bug: Our matchers can't recognize when a `PeerMultiaddr`, when represented as a `Multiaddr`, would match. (the issue I ran into that spawned this PR and https://github.com/multiformats/js-multiaddr-matcher/issues/3)
4. Potential bug: our existing tests because two `goodIPFS` entries seem to have no trailing peerId: https://github.com/multiformats/js-multiaddr-matcher/blob/309e2c4028034b1279f96b805dd951111768cb3b/test/index.spec.ts#L183  & https://github.com/multiformats/js-multiaddr-matcher/blob/309e2c4028034b1279f96b805dd951111768cb3b/test/index.spec.ts#L191

**Comment by SgtPooki** [comment]
chat with alex 2023-08-11

item 1: 
* http multiaddr may not work.. 
* unix sockets because the last entry is a file path (adding to it changes the path.. its a terminal entry in a multiaddr)

in some scenarios (gossipsub), you send peers and multiaddrs for some peers in messages.. 

some scenarios are different:
1. may need to append peerId to multiaddr
2. may need to remove peerIds from multiaddr (gossipsub)

---

sounds like in summary we should add peerId info to multiaddrs in peerstore in js-libp2p. I will create a tracking issue and then close this and #3

**Comment by SgtPooki** [comment]
Closing in favor of https://github.com/libp2p/js-libp2p/issues/1959

**Pull request closed without merging**
